replicaCount: 1

image:
  # repository: ghcr.io/RollerSweet/unleash-devops-home-exercise
  repository: rollersweet/unleash-devops-home-exercise
  tag: "latest"
  pullPolicy: Always

env:
  bucketName: "unleash-home-exercise-bucket-dev"
  port: 3000

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  automount: true
  name: unleash-home-exercise
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::532150070616:role/unleash-home-exercise-app-irsa-dev
