fullnameOverride: unleash-home-exercise

replicaCount: 1

image:
  repository: rollersweet/unleash-home-exercise
  tag: "latest"
  pullPolicy: Always

containerPort: 3000
bucketName: unleash-tm-app-s3-bucket

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: unleash.tamirmadar.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - unleash.tamirmadar.com
      secretName: unleash-tls

serviceAccount:
  create: true
  automount: true
  name: unleash-home-exercise
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::532150070616:role/app-s3-role
